#!/bin/bash
# sd_initialiser
# author: Kevin Grandjean
# date: 23 september 2017
# This script initialises the sd card with the os generated with buildroot.
############
# IMPORTANT:
# This script needs to be run from the folder where the image to put on the card is.
############

# Check if user is root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be executed as root."
    exit 1
fi


# Check if argc is 1
if [[ $# -ne 1 ]]; then
    echo "This script takes only one argument: path to the SD card."
    exit 1
fi


for n in "$1*"; do
    umount $n
done
# init of the first 128MB
dd if=/dev/zero of="$1" bs=4k count=32768


# Creation of the partitions
parted "$1" mklabel msdos
parted "$1" mkpart primary ext4 32768s 163839s
parted "$1" mkpart primary ext4 163840s 688127s
parted "$1" mkpart primary ext4 688128s 1212415s

mkfs.ext4 "${1}1" -L bootfs
mkfs.ext4 "${1}2" -L rootfs
mkfs.ext4 "${1}3" -L usrfs
sync

# Firmware burning
echo "BL1"
dd if=/home/lmi/workspace/xu3/buildroot/output/images/xu3-bl1.bin of="$1" bs=512 seek=1
echo "BL2"
dd if=/home/lmi/workspace/xu3/buildroot/output/images/xu3-bl2.bin of="$1" bs=512 seek=31
echo "TZSW"
dd if=/home/lmi/workspace/xu3/buildroot/output/images/xu3-tzsw.bin of="$1" bs=512 seek=2111
echo "U-Boot"
dd if=/home/lmi/workspace/xu3/buildroot/output/images/xu3-u-boot.bin of="$1" bs=512 seek=63

echo "zImage and exynos"
mkdir ~/mount_point
mount "${1}1" ~/mount_point
cp /home/lmi/workspace/xu3/buildroot/output/images/xu3-zImage ~/mount_point
cp /home/lmi/workspace/xu3/buildroot/output/images/exynos5422-odroidxu3.dtb ~/mount_point
cp /home/lmi/workspace/xu3/buildroot/output/images/uInitrd ~/mount_point

echo "rootfs"
dd if=/home/lmi/workspace/xu3/buildroot/output/images/xu3-rootfs.ext4 of="$1" bs=512 seek=163840
sync

echo "Done copying mate"
sync

for n in "$1*"; do
    umount $n
done

e2fsck -f "${1}2"
resize2fs "${1}2"
